new upstream i40e driver 2.18.9

diff --git a/scripts/set_irq_affinity b/scripts/set_irq_affinity
--- a/scripts/set_irq_affinity
+++ b/scripts/set_irq_affinity
@@ -1,34 +1,12 @@
 #!/bin/bash
-#
-# Copyright (c) 2014, Intel Corporation
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions are met:
-#
-#     * Redistributions of source code must retain the above copyright notice,
-#       this list of conditions and the following disclaimer.
-#     * Redistributions in binary form must reproduce the above copyright
-#       notice, this list of conditions and the following disclaimer in the
-#       documentation and/or other materials provided with the distribution.
-#     * Neither the name of Intel Corporation nor the names of its contributors
-#       may be used to endorse or promote products derived from this software
-#       without specific prior written permission.
-#
-# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
-# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+# SPDX-License-Identifier: BSD-3-Clause
+# Copyright (c) 2015 - 2019, Intel Corporation
 #
 # Affinitize interrupts to cores
 #
 # typical usage is (as root):
 # set_irq_affinity -x local eth1 <eth2> <eth3>
+# set_irq_affinity -s eth1
 #
 # to get help:
 # set_irq_affinity
@@ -36,14 +14,23 @@
 usage()
 {
 	echo
-	echo "Usage: $0 [-x|-X] {all|local|remote|one|custom} [ethX] <[ethY]>"
-	echo "	options: -x		Configure XPS as well as smp_affinity"
-	echo "	options: -X		Disable XPS but set smp_affinity"
-	echo "	options: {remote|one} can be followed by a specific node number"
-	echo "	Ex: $0 local eth0"
-	echo "	Ex: $0 remote 1 eth0"
-	echo "	Ex: $0 custom eth0 eth1"
-	echo "	Ex: $0 0-7,16-23 eth0"
+	echo "Usage: option -s <interface> to show current settings only"
+	echo "Usage: $0 [-x|-X] [all|local|remote [<node>]|one <core>|custom|<cores>] <interface> ..."
+	echo "	Options: "
+	echo "	  -s		Shows current affinity settings"
+	echo "	  -x		Configure XPS as well as smp_affinity"
+	echo "	  -X		Disable XPS but set smp_affinity"
+	echo "	  [all] is the default value"
+	echo "	  [remote [<node>]] can be followed by a specific node number"
+	echo "	Examples:"
+	echo "	  $0 -s eth1            # Show settings on eth1"
+
+	echo "	  $0 all eth1 eth2      # eth1 and eth2 to all cores"
+	echo "	  $0 one 2 eth1         # eth1 to core 2 only"
+	echo "	  $0 local eth1         # eth1 to local cores only"
+	echo "	  $0 remote eth1        # eth1 to remote cores only"
+	echo "	  $0 custom eth1        # prompt for eth1 interface"
+	echo "	  $0 0-7,16-23 eth0     # eth1 to cores 0-7 and 16-23"
 	echo
 	exit 1
 }
@@ -56,6 +43,12 @@ usageX()
 
 if [ "$1" == "-x" ]; then
 	XPS_ENA=1
+	shift
+fi
+
+if [ "$1" == "-s" ]; then
+	SHOW=1
+	echo Show affinity settings
 	shift
 fi
 
@@ -79,7 +72,16 @@ if [ -z "$XPS_ENA" ]; then
 	XPS_ENA=$XPS_DIS
 fi
 
+SED=`which sed`
+if [[ ! -x $SED ]]; then
+	echo " $0: ERROR: sed not found in path, this script requires sed"
+	exit 1
+fi
+
 num='^[0-9]+$'
+
+# search helpers
+NOZEROCOMMA="s/^[0,]*//"
 # Vars
 AFF=$1
 shift
@@ -105,12 +107,23 @@ done
 # for now the user must specify interfaces
 if [ -z "$IFACES" ]; then
 	usage
-	exit 1
+	exit 2
 fi
+
+notfound()
+{
+	echo $MYIFACE: not found
+	exit 15
+}
+
+# check the interfaces exist
+for MYIFACE in $IFACES; do
+	grep -q $MYIFACE /proc/net/dev || notfound
+done
 
 # support functions
 
-set_affinity()
+build_mask()
 {
 	VEC=$core
 	if [ $VEC -ge 32 ]
@@ -130,9 +143,61 @@ set_affinity()
 		MASK_TMP=$((1<<$VEC))
 		MASK=$(printf "%X" $MASK_TMP)
 	fi
+}
+
+show_affinity()
+{
+	# returns the MASK variable
+	build_mask
+
+	SMP_I=`sed -E "${NOZEROCOMMA}" /proc/irq/$IRQ/smp_affinity`
+	HINT=`sed -E "${NOZEROCOMMA}" /proc/irq/$IRQ/affinity_hint`
+	printf "ACTUAL	%s %d %s <- /proc/irq/$IRQ/smp_affinity\n" $IFACE $core $SMP_I
+	printf "HINT 	%s %d %s <- /proc/irq/$IRQ/affinity_hint\n" $IFACE $core $HINT
+	IRQ_CHECK=`grep '[-,]' /proc/irq/$IRQ/smp_affinity_list`
+	if [ ! -z $IRQ_CHECK ]; then
+		printf " WARNING -- SMP_AFFINITY is assigned to multiple cores $IRQ_CHECK\n"
+	fi
+	if [ "$SMP_I" != "$HINT" ]; then
+		printf " WARNING -- SMP_AFFINITY VALUE does not match AFFINITY_HINT \n"
+	fi
+	printf "NODE 	%s %d %s <- /proc/irq/$IRQ/node\n" $IFACE $core `cat /proc/irq/$IRQ/node`
+	printf "LIST	%s %d [%s] <- /proc/irq/$IRQ/smp_affinity_list\n" $IFACE $core `cat /proc/irq/$IRQ/smp_affinity_list`
+	printf "XPS	%s %d %s <- /sys/class/net/%s/queues/tx-%d/xps_cpus\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/xps_cpus` $IFACE $((n-1))
+	if [ -z `ls /sys/class/net/$IFACE/queues/tx-$((n-1))/xps_rxqs` ]; then
+		echo "WARNING: xps rxqs not supported on $IFACE"
+	else
+		printf "XPSRXQs	%s %d %s <- /sys/class/net/%s/queues/tx-%d/xps_rxqs\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/xps_rxqs` $IFACE $((n-1))
+	fi
+	printf "TX_MAX	%s %d %s <- /sys/class/net/%s/queues/tx-%d/tx_maxrate\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/tx_maxrate` $IFACE $((n-1))
+	printf "BQLIMIT	%s %d %s <- /sys/class/net/%s/queues/tx-%d/byte_queue_limits/limit\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/byte_queue_limits/limit` $IFACE $((n-1))
+	printf "BQL_MAX	%s %d %s <- /sys/class/net/%s/queues/tx-%d/byte_queue_limits/limit_max\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/byte_queue_limits/limit_max` $IFACE $((n-1))
+	printf "BQL_MIN	%s %d %s <- /sys/class/net/%s/queues/tx-%d/byte_queue_limits/limit_min\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/tx-$((n-1))/byte_queue_limits/limit_min` $IFACE $((n-1))
+	if [ -z `ls /sys/class/net/$IFACE/queues/rx-$((n-1))/rps_flow_cnt` ]; then
+		echo "WARNING: aRFS is not supported on $IFACE"
+	else
+		printf "RPSFCNT	%s %d %s <- /sys/class/net/%s/queues/rx-%d/rps_flow_cnt\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/rx-$((n-1))/rps_flow_cnt` $IFACE $((n-1))
+	fi
+	if [ -z `ls /sys/class/net/$IFACE/queues/rx-$((n-1))/rps_cpus` ]; then
+		echo "WARNING: rps_cpus is not available on $IFACE"
+	else
+		printf "RPSCPU	%s %d %s <- /sys/class/net/%s/queues/rx-%d/rps_cpus\n" $IFACE $core `cat /sys/class/net/$IFACE/queues/rx-$((n-1))/rps_cpus` $IFACE $((n-1))
+	fi
+	echo
+}
+
+set_affinity()
+{
+	# returns the MASK variable
+	build_mask
 
 	printf "%s" $MASK > /proc/irq/$IRQ/smp_affinity
 	printf "%s %d %s -> /proc/irq/$IRQ/smp_affinity\n" $IFACE $core $MASK
+	SMP_I=`sed -E "${NOZEROCOMMA}" /proc/irq/$IRQ/smp_affinity`
+	if [ "$SMP_I" != "$MASK" ]; then
+		printf " ACTUAL\t%s %d %s <- /proc/irq/$IRQ/smp_affinity\n" $IFACE $core $SMP_I
+		printf " WARNING -- SMP_AFFINITY setting failed\n"
+	fi
 	case "$XPS_ENA" in
 	1)
 		printf "%s %d %s -> /sys/class/net/%s/queues/tx-%d/xps_cpus\n" $IFACE $core $MASK $IFACE $((n-1))
@@ -163,7 +228,7 @@ parse_range () {
 
 # Affinitize interrupts
 #
-setaff()
+doaff()
 {
 	CORES=$(parse_range $CORES)
 	ncores=$(echo $CORES | wc -w)
@@ -177,13 +242,17 @@ setaff()
 
 	irqs=$(grep "$queues" /proc/interrupts | cut -f1 -d:)
 	[ -z "$irqs" ] && irqs=$(grep $IFACE /proc/interrupts | cut -f1 -d:)
-	[ -z "$irqs" ] && irqs=$(for i in `ls -Ux /sys/class/net/$IFACE/device/msi_irqs` ;\
-	                         do grep "$i:.*TxRx" /proc/interrupts | grep -v fdir | cut -f 1 -d : ;\
-	                         done)
+	[ -z "$irqs" ] && irqs=$(for i in `ls -1 /sys/class/net/${IFACE}/device/msi_irqs | sort -n` ;do grep -w $i: /proc/interrupts | egrep -v 'fdir|async|misc|ctrl' | cut -f 1 -d :; done)
 	[ -z "$irqs" ] && echo "Error: Could not find interrupts for $IFACE"
 
-	echo "IFACE CORE MASK -> FILE"
-	echo "======================="
+	if [ "$SHOW" == "1" ] ; then
+		echo "TYPE IFACE CORE MASK -> FILE"
+		echo "============================"
+	else
+		echo "IFACE CORE MASK -> FILE"
+		echo "======================="
+	fi
+
 	for IRQ in $irqs; do
 		[ "$n" -gt "$ncores" ] && n=1
 		j=1
@@ -192,12 +261,14 @@ setaff()
 			[ $((j++)) -ge $n ] && break
 		done
 		core=$i
-		set_affinity
+		if [ "$SHOW" == "1" ] ; then
+			show_affinity
+		else
+			set_affinity
+		fi
 		((n++))
 	done
 }
-
-# now the actual useful bits of code
 
 # these next 2 lines would allow script to auto-determine interfaces
 #[ -z "$IFACES" ] && IFACES=$(ls /sys/class/net)
@@ -251,7 +322,7 @@ for IFACE in $IFACES; do
 	esac
 
 	# call the worker function
-	setaff
+	doaff
 done
 
 # check for irqbalance running
@@ -261,4 +332,5 @@ if [ "$IRQBALANCE_ON" == "0" ] ; then
 	echo "          likely override this script's affinitization."
 	echo "          Please stop the irqbalance service and/or execute"
 	echo "          'killall irqbalance'"
+	exit 2
 fi
